name: Build and Push Docker Image

on:
  push:
    branches:
      - main
# agregando el workflow para que se ejecute en cada push a la rama main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        run: | 
          npm run dockerbuild:prod

      - name: Login and push to Docker Hub
        run: |
          docker login -u elsoloeres -p  ${{ secrets.TOKEN_DOCKER_HUB }}
          docker tag nochedoradaimagen:latest elsoloeres/nochedoradaimagen:latest
          docker push elsoloeres/nochedoradaimagen:latest
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull elsoloeres/nochedoradaimagen:latest
            cd /root/github-docker/nochedorada-docker
            docker compose up -d